#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWT.DiscoPlugin.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco.Models.Repository;
    using Disco.Services.Authorization;
    using Disco.Services.Plugins;
    using Disco.Services.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Configuration.cshtml")]
    public partial class Configuration : Disco.Services.Plugins.PluginWebViewPage<LWT.DiscoPlugin.Models.ConfigurationModel>
    {
        public Configuration()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(" style=\"width: 750px; margin: 0 auto 0 auto;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" style=\"float: left; width: 300px; text-align: center; padding-top: 40px;\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"http://www.lwt.com.au/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 279), Tuple.Create("\"", 319)
            
            #line 5 "..\..\Views\Configuration.cshtml"
, Tuple.Create(Tuple.Create("", 285), Tuple.Create<System.Object, System.Int32>(Plugin.ResourceUrl("LWTLogo.png")
            
            #line default
            #line hidden
, 285), false)
);

WriteLiteral(" alt=\"LWT Logo\"");

WriteLiteral(" style=\"width: 213px; height: 48px;\"");

WriteLiteral(" /></a></div>\r\n    <div");

WriteLiteral(" class=\"form\"");

WriteLiteral(" style=\"float: left; width: 450px\"");

WriteLiteral(">\r\n        <h2>\r\n            Customer Identification Details</h2>\r\n        <table" +
">\r\n            <tr>\r\n                <th");

WriteLiteral(" style=\"width: 160px\"");

WriteLiteral(">\r\n                    Customer Entity Id:\r\n                </th>\r\n              " +
"  <td>\r\n");

WriteLiteral("                    ");

            
            #line 15 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.CustomerEntityId));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

WriteLiteral("                    ");

            
            #line 16 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.CustomerEntityId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
"");

WriteLiteral(" style=\"width: 160px\"");

WriteLiteral(">\r\n                    Customer Username:\r\n                </th>\r\n               " +
" <td>\r\n");

WriteLiteral("                    ");

            
            #line 24 "..\..\Views\Configuration.cshtml"
               Write(Html.EditorFor(m => m.CustomerUsername));

            
            #line default
            #line hidden
WriteLiteral("<br />\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Views\Configuration.cshtml"
               Write(Html.ValidationMessageFor(m => m.CustomerUsername));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n        </table>\r\n        <p>\r\n      " +
"      <strong>Note:</strong> If you don\'t know these details, please contact <a");

WriteLiteral(" href=\"http://www.lwt.com.au/\"");

WriteLiteral("\r\n                target=\"_blank\"");

WriteLiteral(">Learning&nbsp;With&nbsp;Technology</a> for support (Service\r\n            Desk: 1" +
"300 556 788).</p>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
