#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWT.DiscoPlugin.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Disco.Services.Plugins;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/WarrantyJobDetails.cshtml")]
    public partial class WarrantyJobDetails : System.Web.Mvc.WebViewPage<LWT.DiscoPlugin.Models.WarrantyJobDetailsModel>
    {
        public WarrantyJobDetails()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" id=\"LWTWarrantyProviderJobDetails\"");

WriteLiteral(">\r\n");

            
            #line 3 "..\..\Views\WarrantyJobDetails.cshtml"
    
            
            #line default
            #line hidden
            
            #line 3 "..\..\Views\WarrantyJobDetails.cshtml"
     if (Model == null || !Model.JobDetailsParsed)
    {

            
            #line default
            #line hidden
WriteLiteral("        <table>\r\n            <tr>\r\n                <td");

WriteLiteral(" style=\"text-align: center; vertical-align: middle;\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">Unable to provide details for this Job</span>\r\n                </td>\r\n          " +
"      <td");

WriteLiteral(" rowspan=\"3\"");

WriteLiteral(" style=\"width: 300px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"text-align: center; padding-top: 10px;\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://www.lwt.com.au/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 619), Tuple.Create("\"", 668)
            
            #line 13 "..\..\Views\WarrantyJobDetails.cshtml"
, Tuple.Create(Tuple.Create("", 625), Tuple.Create<System.Object, System.Int32>(this.DiscoPluginResourceUrl("LWTLogo.png")
            
            #line default
            #line hidden
, 625), false)
);

WriteLiteral(" alt=\"LWT Logo\"");

WriteLiteral(" style=\"width: 213px; height: 48px;\"");

WriteLiteral(" />\r\n                        </a>\r\n                    </div>\r\n                </" +
"td>\r\n            </tr>\r\n        </table>\r\n");

            
            #line 19 "..\..\Views\WarrantyJobDetails.cshtml"
    }
    else
    { 

            
            #line default
            #line hidden
WriteLiteral("        <table>\r\n            <tr>\r\n                <th");

WriteLiteral(" style=\"width: 120px;\"");

WriteLiteral(">LWT Job Ids:\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 27 "..\..\Views\WarrantyJobDetails.cshtml"
               Write(Model.LWTJobId);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n                <td");

WriteLiteral(" rowspan=\"3\"");

WriteLiteral(" style=\"width: 300px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"text-align: center; padding-top: 10px;\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"http://www.lwt.com.au/\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">\r\n                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1301), Tuple.Create("\"", 1350)
            
            #line 32 "..\..\Views\WarrantyJobDetails.cshtml"
, Tuple.Create(Tuple.Create("", 1307), Tuple.Create<System.Object, System.Int32>(this.DiscoPluginResourceUrl("LWTLogo.png")
            
            #line default
            #line hidden
, 1307), false)
);

WriteLiteral(" alt=\"LWT Logo\"");

WriteLiteral(" style=\"width: 213px; height: 48px;\"");

WriteLiteral(" /></a>\r\n                    </div>\r\n                </td>\r\n            </tr>\r\n  " +
"          <tr>\r\n                <th");

WriteLiteral(" style=\"width: 120px;\"");

WriteLiteral(">Date Logged:\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 40 "..\..\Views\WarrantyJobDetails.cshtml"
               Write(Model.DateLogged);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
"");

WriteLiteral(" style=\"width: 120px;\"");

WriteLiteral(">Date Completed:\r\n                </th>\r\n                <td>\r\n");

WriteLiteral("                    ");

            
            #line 47 "..\..\Views\WarrantyJobDetails.cshtml"
               Write(Model.DateCompleted);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n            <tr>\r\n                <th" +
"");

WriteLiteral(" style=\"width: 120px;\"");

WriteLiteral(">Fault Description:\r\n                </th>\r\n                <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 54 "..\..\Views\WarrantyJobDetails.cshtml"
                Write(new HtmlString(Model.FaultDescription));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </td>\r\n            </tr>\r\n        </table>\r\n");

            
            #line 58 "..\..\Views\WarrantyJobDetails.cshtml"
        

            
            #line default
            #line hidden
WriteLiteral("        <h3>Actions</h3>\r\n");

            
            #line 60 "..\..\Views\WarrantyJobDetails.cshtml"
        if (Model.Actions == null || Model.Actions.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("        <span");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(">No actions founds</span>\r\n");

            
            #line 63 "..\..\Views\WarrantyJobDetails.cshtml"
        }
        else
        { 

            
            #line default
            #line hidden
WriteLiteral("        <table>\r\n            <tr>\r\n                <th");

WriteLiteral(" style=\"text-align: left; width: 80px;\"");

WriteLiteral(">Type\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align: left; width: 100px;\"");

WriteLiteral(">Date\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align: left; width: auto;\"");

WriteLiteral(">Action Description\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align: left; width: 120px;\"");

WriteLiteral(">Technician Id\r\n                </th>\r\n            </tr>\r\n");

            
            #line 77 "..\..\Views\WarrantyJobDetails.cshtml"
            
            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\WarrantyJobDetails.cshtml"
             foreach (var action in Model.Actions)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");

            
            #line 80 "..\..\Views\WarrantyJobDetails.cshtml"
                   Write(action.Type);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>");

            
            #line 82 "..\..\Views\WarrantyJobDetails.cshtml"
                   Write(action.Date);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>");

            
            #line 84 "..\..\Views\WarrantyJobDetails.cshtml"
                    Write(new HtmlString(action.ActionDescription));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>");

            
            #line 86 "..\..\Views\WarrantyJobDetails.cshtml"
                   Write(action.TechnicianId);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n");

            
            #line 89 "..\..\Views\WarrantyJobDetails.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </table> \r\n");

            
            #line 91 "..\..\Views\WarrantyJobDetails.cshtml"
        }
        var cacheAge = DateTime.Now.Subtract(Model.CacheAge);
        if (cacheAge.TotalSeconds > 1)
        {
            var cacheMinutes = (int)cacheAge.TotalMinutes;

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"smallMessage\"");

WriteLiteral(" style=\"text-align: right; margin-top: 4px;\"");

WriteLiteral(">\r\n            Retrieved ");

            
            #line 97 "..\..\Views\WarrantyJobDetails.cshtml"
                  Write(cacheMinutes);

            
            #line default
            #line hidden
WriteLiteral("\r\n            minute");

            
            #line 98 "..\..\Views\WarrantyJobDetails.cshtml"
                    if (cacheMinutes != 1)
                    {
            
            #line default
            #line hidden
WriteLiteral("s");

            
            #line 99 "..\..\Views\WarrantyJobDetails.cshtml"
                                   ;
                    }
            
            #line default
            #line hidden
WriteLiteral("\r\n            ago\r\n        </div>\r\n");

            
            #line 103 "..\..\Views\WarrantyJobDetails.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("</div>");

        }
    }
}
#pragma warning restore 1591
